apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfo-rule
  namespace: blue-apps
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/public-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9898
        host: podinfo